export { default as About} from './About/index';
// export { default as AnimatedLetters } from './AnimatedLetters/index';
export { default as Contact} from './Contact/index';
export { default as Home } from './Home/index';
export { default as Layout} from './Layout/index';
export { default as Login } from './Login/index';
export { default as NewEntry} from './NewEntry/index';
export { default as Protected} from './Protected/index';
export { default as PublicSidebar} from './PublicSidebar/index';
export { default as Register} from './Register/index';
export { default as Search} from './Search/index';
export { default as Settings } from './Settings/index';
export { default as Sidebar} from './Sidebar/index';