# Generated by Django 5.2.4 on 2025-07-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediaitem',
            unique_together={('title', 'media_type')},
        ),
    ]
