# Generated by Django 5.2.4 on 2025-07-18 00:04

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_mediaitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermediaentry',
            name='grade',
            field=models.CharField(choices=[('S+', 'S+'), ('S', 'S'), ('S-', 'S-'), ('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], default='C', help_text='Letter grade', max_length=2),
        ),
        migrations.AlterField(
            model_name='usermediaentry',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usermediaentry',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Numeric rating out of 10 (e.g., 7.5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterUniqueTogether(
            name='usermediaentry',
            unique_together={('user', 'media')},
        ),
    ]
