# Generated by Django 5.2.4 on 2025-07-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_mediaitem_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediaitem',
            unique_together={('title', 'media_type', 'creator')},
        ),
    ]
